micronaut:
  application:
    name: clienteService

#datasources:
#  default:
#    url: ${JDBC_URL:`jdbc:h2:file:./db_curso;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
#    username: ${JDBC_USER:sa}
#    password: ${JDBC_PASSWORD:""}
#    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/cliente-db`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    dialect: MYSQL

jpa:
  default:
    packages-to-scan:
      - 'br.com.marcelodaniel'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
